#pragma once

#include <map>
#include <vector>

#include "wave_function_colapse_generator.hpp"

std::map<TileType, std::map<Direction, std::vector<TileType>>>
    possibility_matrix{
        {
            TileType::TopLeftWall,
            {{Direction::Up,
              {
                  TileType::Grass,
                  TileType::TUp,
                  TileType::BottomLeftRoad,
                  TileType::BottomRightRoad,
                  TileType::HorizontalRoad,
              }},
             {Direction::Left,
              {
                  TileType::Grass,
                  TileType::TLeft,
                  TileType::BottomRightRoad,
                  TileType::TopRightRoad,
                  TileType::VerticalRoad,
              }},
             {Direction::Right,
              {
                  TileType::TopWall,
                  TileType::TopRightWall,
                  TileType::TRight,
                  TileType::TopLeftWall,
                  TileType::BottomLeftRoad,
                  TileType::VerticalRoad,
                  TileType::Grass,
              }},
             {Direction::Down,
              {
                  TileType::LeftWall,
                  TileType::BottomLeftWall,
                  TileType::TDown,
                  TileType::TopLeftRoad,
                  TileType::TopRightRoad,
                  TileType::HorizontalRoad,
              }}},
        },
        {
            TileType::TopWall,
            {{Direction::Up,
              {TileType::Grass, TileType::TUp, TileType::BottomLeftRoad,
               TileType::BottomRightRoad}},
             {Direction::Left,
              {TileType::TopWall, TileType::TopLeftWall, TileType::VerticalRoad,
               TileType::TLeft, TileType::TopRightRoad,
               TileType::BottomRightRoad}},
             {Direction::Right,
              {TileType::TopWall, TileType::TopRightWall,
               TileType::VerticalRoad, TileType::TRight, TileType::TopLeftRoad,
               TileType::BottomLeftRoad}},
             {Direction::Down,
              {TileType::Grass, TileType::TDown, TileType::TopLeftRoad,
               TileType::TopRightRoad, TileType::HorizontalRoad}}},
        },
        {
            TileType::TopRightWall,
            {{Direction::Up,
              {TileType::Grass, TileType::TUp, TileType::BottomRightRoad,
               TileType::BottomLeftRoad, TileType::HorizontalRoad}},
             {Direction::Left,
              {TileType::TopWall, TileType::TopLeftWall, TileType::Grass,
               TileType::TLeft, TileType::BottomRightRoad,
               TileType::TopRightRoad, TileType::VerticalRoad}},
             {Direction::Right,
              {TileType::Grass, TileType::TRight, TileType::TopLeftRoad,
               TileType::BottomLeftRoad, TileType::VerticalRoad}},
             {Direction::Down,
              {TileType::RightWall, TileType::BottomRightWall,
               TileType::HorizontalRoad, TileType::Grass, TileType::TDown,
               TileType::TopRightRoad, TileType::TopLeftRoad}}},

        },
        {
            TileType::LeftWall,
            {{Direction::Up,
              {TileType::LeftWall, TileType::TopLeftWall, TileType::TUp,
               TileType::BottomLeftWall, TileType::BottomRightWall,
               TileType::HorizontalRoad, TileType::Grass}},
             {Direction::Left,
              {TileType::Grass, TileType::TLeft, TileType::BottomRightRoad,
               TileType::TopRightRoad, TileType::VerticalRoad}},
             {Direction::Right,
              {TileType::Grass, TileType::TRight, TileType::TopLeftRoad,
               TileType::BottomLeftRoad, TileType::VerticalRoad}},
             {Direction::Down,
              {TileType::LeftWall, TileType::BottomLeftWall, TileType::TDown,
               TileType::HorizontalRoad, TileType::Grass, TileType::TopLeftRoad,
               TileType::TopRightRoad}}},

        },
        {
            TileType::RightWall,
            {{Direction::Up,
              {TileType::RightWall, TileType::TopRightWall,
               TileType::HorizontalRoad, TileType::TUp,
               TileType::BottomLeftRoad, TileType::BottomRightRoad}},
             {Direction::Left,
              {TileType::Grass, TileType::TLeft, TileType::TopRightRoad,
               TileType::BottomRightRoad, TileType::VerticalRoad}},
             {Direction::Right,
              {TileType::Grass, TileType::TRight, TileType::BottomLeftRoad,
               TileType::TopLeftRoad, TileType::VerticalRoad}},
             {Direction::Down,
              {TileType::RightWall, TileType::BottomRightWall,
               TileType::HorizontalRoad, TileType::TDown, TileType::TopLeftRoad,
               TileType::TopRightRoad}}},
        },
        {
            TileType::BottomLeftWall,
            {{Direction::Up,
              {TileType::LeftWall, TileType::TopLeftWall,
               TileType::HorizontalRoad, TileType::TUp, TileType::Grass,
               TileType::BottomLeftRoad, TileType::BottomRightRoad}},
             {Direction::Left,
              {TileType::Grass, TileType::TLeft, TileType::TopRightRoad,
               TileType::BottomRightRoad, TileType::VerticalRoad}},
             {Direction::Right,
              {TileType::BottomWall, TileType::BottomRightWall, TileType::Grass,
               TileType::VerticalRoad, TileType::TRight, TileType::TopLeftRoad,
               TileType::BottomLeftRoad}},
             {Direction::Down,
              {TileType::Grass, TileType::HorizontalRoad, TileType::TDown,
               TileType::TopLeftRoad, TileType::TopRightRoad}}},

        },
        {
            TileType::BottomWall,
            {{Direction::Up,
              {TileType::Grass, TileType::TUp, TileType::BottomLeftRoad,
               TileType::BottomRightRoad, TileType::HorizontalRoad}},
             {Direction::Left,
              {TileType::BottomWall, TileType::BottomLeftWall,
               TileType::VerticalRoad, TileType::TLeft, TileType::TopRightRoad,
               TileType::BottomRightRoad, TileType::Grass}},
             {Direction::Right,
              {TileType::BottomWall, TileType::BottomRightWall,
               TileType::VerticalRoad, TileType::TRight,
               TileType::BottomLeftRoad, TileType::TopLeftRoad,
               TileType::Grass}},
             {Direction::Down,
              {TileType::Grass, TileType::TDown, TileType::TopLeftRoad,
               TileType::TopRightRoad, TileType::HorizontalRoad}}},

        },
        {
            TileType::BottomRightWall,
            {{Direction::Up,
              {TileType::RightWall, TileType::TopRightWall, TileType::TUp,
               TileType::BottomRightRoad, TileType::BottomLeftRoad,
               TileType::HorizontalRoad}},
             {Direction::Left,
              {TileType::BottomWall, TileType::BottomLeftWall, TileType::TLeft,
               TileType::TopRightRoad, TileType::BottomRightRoad,
               TileType::VerticalRoad}},
             {Direction::Right,
              {TileType::Grass, TileType::TRight, TileType::VerticalRoad,
               TileType::BottomLeftRoad, TileType::TopLeftRoad}},
             {Direction::Down,
              {TileType::Grass, TileType::HorizontalRoad, TileType::TDown,
               TileType::TopLeftRoad, TileType::TopRightRoad}}},
        },
        {
            TileType::TopLeftRoad,
            {{Direction::Up,
              {TileType::Grass, TileType::TopWall, TileType::BottomLeftRoad,
               TileType::BottomRightRoad, TileType::TUp}},
             {Direction::Left,
              {TileType::Grass, TileType::LeftWall, TileType::TLeft,
               TileType::BottomRightRoad, TileType::TopRightRoad}},
             {Direction::Right,
              {TileType::TopRightRoad, TileType::BottomRightRoad,
               TileType::TLeft, TileType::TUp, TileType::TDown,
               TileType::CrossRoads}},
             {Direction::Down,
              {TileType::TUp, TileType::TLeft, TileType::TRight,
               TileType::BottomRightRoad, TileType::BottomLeftRoad,
               TileType::CrossRoads}}},
        },
        {
            TileType::TDown,
            {{Direction::Up,
              {TileType::Grass, TileType::TopWall, TileType::TUp,
               TileType::BottomLeftRoad, TileType::BottomRightRoad}},
             {Direction::Left,
              {TileType::TDown, TileType::CrossRoads, TileType::TRight,
               TileType::TUp, TileType::BottomLeftRoad, TileType::TopLeftRoad}},
             {Direction::Right,
              {TileType::TDown, TileType::CrossRoads, TileType::TLeft,
               TileType::TUp, TileType::BottomRightRoad,
               TileType::TopRightRoad}},
             {Direction::Down,
              {TileType::CrossRoads, TileType::TUp, TileType::TLeft,
               TileType::TRight, TileType::BottomRightRoad,
               TileType::BottomLeftRoad}}},
        },
        {
            TileType::TopRightRoad,
            {{Direction::Up,
              {TileType::Grass, TileType::TopWall, TileType::BottomLeftRoad,
               TileType::BottomRightRoad, TileType::TUp,
               TileType::HorizontalRoad}},
             {Direction::Left,
              {TileType::TopLeftRoad, TileType::BottomLeftRoad,
               TileType::TRight, TileType::TUp, TileType::TDown,
               TileType::CrossRoads, TileType::HorizontalRoad}},
             {Direction::Right,
              {TileType::Grass, TileType::RightWall, TileType::TRight,
               TileType::BottomLeftRoad, TileType::TopLeftRoad,
               TileType::VerticalRoad}},
             {Direction::Down,
              {TileType::TUp, TileType::TLeft, TileType::TRight,
               TileType::BottomRightRoad, TileType::BottomLeftRoad,
               TileType::CrossRoads, TileType::VerticalRoad}}},
        },
        {
            TileType::TRight,
            {{Direction::Up,
              {TileType::TRight, TileType::TLeft, TileType::TDown,
               TileType::CrossRoads, TileType::TopLeftRoad,
               TileType::TopRightRoad, TileType::VerticalRoad}},
             {Direction::Left,
              {TileType::Grass, TileType::TLeft, TileType::TopRightRoad,
               TileType::BottomRightRoad}},
             {Direction::Right,
              {TileType::TLeft, TileType::TUp, TileType::TDown,
               TileType::TopRightRoad, TileType::BottomRightRoad,
               TileType::CrossRoads, TileType::HorizontalRoad}},
             {Direction::Down,
              {TileType::TRight, TileType::TUp, TileType::TLeft,
               TileType::BottomLeftRoad, TileType::BottomRightRoad,
               TileType::CrossRoads, TileType::VerticalRoad}}},
        },
        {
            TileType::CrossRoads,
            {{Direction::Up,
              {TileType::TDown, TileType::TLeft, TileType::TRight,
               TileType::TopRightRoad, TileType::TopLeftRoad,
               TileType::CrossRoads}},
             {Direction::Left,
              {TileType::TRight, TileType::TUp, TileType::TDown,
               TileType::BottomLeftRoad, TileType::TopLeftRoad,
               TileType::CrossRoads}},
             {Direction::Right,
              {TileType::TLeft, TileType::TUp, TileType::TDown,
               TileType::BottomRightRoad, TileType::TopRightRoad,
               TileType::CrossRoads}},
             {Direction::Down,
              {TileType::TUp, TileType::TRight, TileType::TLeft,
               TileType::BottomLeftRoad, TileType::BottomRightRoad,
               TileType::CrossRoads}}},
        },
        {
            TileType::TLeft,
            {{Direction::Up,
              {TileType::TLeft, TileType::TRight, TileType::TDown,
               TileType::TopLeftRoad, TileType::TopRightRoad,
               TileType::CrossRoads}},
             {Direction::Left,
              {TileType::TRight, TileType::TUp, TileType::TDown,
               TileType::BottomLeftRoad, TileType::TopLeftRoad,
               TileType::CrossRoads}},
             {Direction::Right,
              {TileType::TRight, TileType::BottomLeftWall,
               TileType::TopLeftWall, TileType::Grass, TileType::RightWall}},
             {Direction::Down,
              {TileType::TLeft, TileType::TUp, TileType::TRight,
               TileType::BottomLeftRoad, TileType::BottomRightRoad,
               TileType::CrossRoads}}},
        },
        {
            TileType::BottomLeftRoad,
            {{Direction::Up,
              {TileType::TDown, TileType::TLeft, TileType::TRight,
               TileType::TopLeftRoad, TileType::TopRightRoad,
               TileType::CrossRoads}},
             {Direction::Left,
              {TileType::TLeft, TileType::BottomRightRoad,
               TileType::TopRightRoad, TileType::Grass, TileType::LeftWall,
               TileType::TopRightWall}},
             {Direction::Right,
              {TileType::TLeft, TileType::TUp, TileType::TDown,
               TileType::BottomRightRoad, TileType::TopRightRoad,
               TileType::CrossRoads}},
             {Direction::Down,
              {TileType::Grass, TileType::BottomWall, TileType::TopRightRoad,
               TileType::TopRightRoad, TileType::TopLeftRoad, TileType::TDown,
               TileType::TopWall, TileType::TopLeftWall,
               TileType::TopRightWall}}},
        },
        {
            TileType::TUp,
            {{Direction::Up,
              {TileType::TDown, TileType::TLeft, TileType::TRight,
               TileType::TopLeftRoad, TileType::TopRightRoad,
               TileType::CrossRoads}},
             {Direction::Left,
              {TileType::TUp, TileType::TDown, TileType::TRight,
               TileType::TopLeftRoad, TileType::BottomLeftRoad,
               TileType::CrossRoads}},
             {Direction::Right,
              {TileType::TUp, TileType::TLeft, TileType::TDown,
               TileType::BottomRightRoad, TileType::TopRightRoad,
               TileType::CrossRoads}},
             {Direction::Down,
              {TileType::Grass, TileType::BottomWall, TileType::TDown,
               TileType::TopRightRoad, TileType::TopLeftRoad}}},
        },
        {
            TileType::BottomRightRoad,
            {{Direction::Up,
              {TileType::TLeft, TileType::TRight, TileType::TDown,
               TileType::TopLeftRoad, TileType::TopRightRoad,
               TileType::CrossRoads}},
             {Direction::Left,
              {TileType::TUp, TileType::TDown, TileType::TRight,
               TileType::TopLeftRoad, TileType::BottomLeftRoad,
               TileType::CrossRoads}},
             {Direction::Right,
              {TileType::Grass, TileType::RightWall, TileType::TRight,
               TileType::TopLeftRoad, TileType::BottomLeftRoad}},
             {Direction::Down,
              {TileType::Grass, TileType::BottomWall, TileType::TDown,
               TileType::TopLeftRoad, TileType::TopRightRoad}}},
        },
        {
            TileType::Grass,
            {{Direction::Up,
              {TileType::TopWall, TileType::TUp, TileType::BottomLeftRoad,
               TileType::BottomRightRoad, TileType::Grass,
               TileType::HorizontalRoad}},
             {Direction::Left,
              {TileType::LeftWall, TileType::TLeft, TileType::TopRightRoad,
               TileType::BottomRightRoad, TileType::Grass,
               TileType::VerticalRoad}},
             {Direction::Right,
              {TileType::RightWall, TileType::TRight, TileType::TopLeftRoad,
               TileType::BottomLeftRoad, TileType::Grass,
               TileType::VerticalRoad}},
             {Direction::Down,
              {TileType::BottomWall, TileType::TDown, TileType::TopLeftRoad,
               TileType::TopRightRoad, TileType::Grass,
               TileType::HorizontalRoad}}},
        },
        {
            TileType::VerticalRoad,
            {{Direction::Up,
              {TileType::CrossRoads, TileType::TDown, TileType::TLeft,
               TileType::TRight, TileType::TopLeftRoad, TileType::TopRightRoad,
               TileType::VerticalRoad}},
             {Direction::Left,
              {TileType::LeftWall, TileType::RightWall, TileType::TLeft,
               TileType::TopRightRoad, TileType::BottomRightRoad,
               TileType::Grass}},
             {Direction::Right,
              {TileType::RightWall, TileType::LeftWall, TileType::TRight,
               TileType::TopLeftRoad, TileType::BottomLeftRoad,
               TileType::Grass}},
             {Direction::Down,
              {TileType::CrossRoads, TileType::TUp, TileType::TLeft,
               TileType::TRight, TileType::BottomLeftRoad,
               TileType::BottomRightRoad, TileType::VerticalRoad}}},
        },
        {
            TileType::HorizontalRoad,
            {{Direction::Up,
              {TileType::Grass, TileType::TopWall, TileType::BottomWall,
               TileType::TUp, TileType::BottomLeftRoad,
               TileType::BottomLeftWall, TileType::BottomRightRoad,
               TileType::BottomRightWall}},
             {Direction::Left,
              {TileType::CrossRoads, TileType::TRight, TileType::TUp,
               TileType::TDown, TileType::BottomLeftRoad, TileType::TopLeftRoad,
               TileType::HorizontalRoad}},
             {Direction::Right,
              {TileType::CrossRoads, TileType::TLeft, TileType::TUp,
               TileType::TDown, TileType::BottomRightRoad,
               TileType::TopRightRoad, TileType::HorizontalRoad}},
             {Direction::Down,
              {TileType::Grass, TileType::TopWall, TileType::BottomWall,
               TileType::TopRightRoad, TileType::TopRightWall,
               TileType::TopLeftRoad, TileType::TopRightWall,
               TileType::TDown}}},
        },
    };